---
- name: Creating  a file and directory on remote server
  hosts: myhosts
  tasks:
   - name:  Creating a file
     file:
      path: /home/myuser/newFile.txt
      state: touch
      owner: myuser
      group: myuser
      mode: u=rwx,g=rw,o=r
  
   - name: Creating a directory
     file:
      path: /home/myuser/newDir
      state: directory  
